-- MS SQL SERVER

WITH T1 AS
(SELECT SUBMISSION_DATE,
HACKER_ID,
DENSE_RANK() OVER(ORDER BY SUBMISSION_DATE ASC) AS RNK1,
DENSE_RANK() OVER(PARTITION BY HACKER_ID ORDER BY SUBMISSION_DATE ASC) AS RNK2
FROM SUBMISSIONS),

-- NUMBER OF UNIQUE HACKERS WHO SUBMITS EVERYDAY
T2 AS
(SELECT SUBMISSION_DATE,
COUNT(DISTINCT HACKER_ID) AS CNT
FROM T1
WHERE RNK1 = RNK2
GROUP BY
SUBMISSION_DATE),

-- HACKERS WHO SUBMITTED MOST REGARDLESS OF BEING UNIQUE 
T3 AS
(SELECT SUBMISSION_DATE,
SUBMISSIONS.HACKER_ID,
NAME,
COUNT(SUBMISSIONS.HACKER_ID) AS CNT,
ROW_NUMBER() OVER(PARTITION BY SUBMISSION_DATE ORDER BY COUNT(SUBMISSIONS.HACKER_ID) DESC, SUBMISSIONS.HACKER_ID ASC) AS RN
FROM SUBMISSIONS
INNER JOIN HACKERS
ON HACKERS.HACKER_ID = SUBMISSIONS.HACKER_ID
GROUP BY
SUBMISSION_DATE,
SUBMISSIONS.HACKER_ID,
NAME)

SELECT T2.SUBMISSION_DATE,
T2.CNT,
HACKER_ID,
NAME
FROM T3
INNER JOIN T2
ON T2.SUBMISSION_DATE = T3.SUBMISSION_DATE
WHERE RN = 1
ORDER BY
T2.SUBMISSION_DATE ASC
