--MS SQL SERVER

WITH TOP_FIFTY AS
(
    SELECT TOP 50 PERCENT LAT_N    
    FROM STATION
    ORDER BY LAT_N ASC
),

BOTTOM_FIFTY AS
(
    SELECT TOP 50 PERCENT LAT_N    
    FROM STATION
    ORDER BY LAT_N DESC
)

SELECT CAST((MAX(TF.LAT_N) + MIN(BF.LAT_N))/2 AS DECIMAL(10, 4))
FROM TOP_FIFTY AS TF,
     BOTTOM_FIFTY AS BF
