-- MS SQL SERVER

WITH VIEW_TABLE AS
(SELECT CON.CONTEST_ID,
SUM(TOTAL_VIEWS) AS SUM_TOTAL_VIEWS,
SUM(TOTAL_UNIQUE_VIEWS) AS SUM_TOTAL_UNIQUE_VIEWS
FROM VIEW_STATS VS
INNER JOIN CHALLENGES CH
ON CH.CHALLENGE_ID = VS.CHALLENGE_ID
INNER JOIN COLLEGES CO
ON CO.COLLEGE_ID = CH.COLLEGE_ID
INNER JOIN CONTESTS CON
ON CON.CONTEST_ID = CO.CONTEST_ID
GROUP BY CON.CONTEST_ID),

SUBMISSION_TABLE AS
(SELECT CON.CONTEST_ID,
SUM(TOTAL_SUBMISSIONS) AS SUM_TOTAL_SUBMISSIONS,
SUM(TOTAL_ACCEPTED_SUBMISSIONS) AS SUM_TOTAL_ACCEPTED_SUBMISSIONS
FROM SUBMISSION_STATS SS
INNER JOIN CHALLENGES CH
ON CH.CHALLENGE_ID = SS.CHALLENGE_ID
INNER JOIN COLLEGES CO
ON CO.COLLEGE_ID = CH.COLLEGE_ID
INNER JOIN CONTESTS CON
ON CON.CONTEST_ID = CO.CONTEST_ID
GROUP BY CON.CONTEST_ID)

SELECT C.CONTEST_ID,
C.HACKER_ID,
C.NAME,
ST.SUM_TOTAL_SUBMISSIONS,
ST.SUM_TOTAL_ACCEPTED_SUBMISSIONS,
VT.SUM_TOTAL_VIEWS,
VT.SUM_TOTAL_UNIQUE_VIEWS
FROM CONTESTS C
INNER JOIN SUBMISSION_TABLE ST
ON ST.CONTEST_ID = C.CONTEST_ID
INNER JOIN VIEW_TABLE VT
ON VT.CONTEST_ID = C.CONTEST_ID
WHERE
VT.SUM_TOTAL_VIEWS > 0
AND
VT.SUM_TOTAL_UNIQUE_VIEWS > 0
AND
ST.SUM_TOTAL_SUBMISSIONS > 0
AND
ST.SUM_TOTAL_ACCEPTED_SUBMISSIONS > 0
ORDER BY
C.CONTEST_ID ASC
