--MS SQL SERVER

WITH SS AS
(
SELECT CONTESTS.CONTEST_ID,
       SUM(SUBMISSION_STATS.TOTAL_SUBMISSIONS) AS SUM_TS,
       SUM(SUBMISSION_STATS.TOTAL_ACCEPTED_SUBMISSIONS) AS SUM_TAS
FROM SUBMISSION_STATS
INNER JOIN CHALLENGES
ON CHALLENGES.CHALLENGE_ID = SUBMISSION_STATS.CHALLENGE_ID
INNER JOIN COLLEGES
ON COLLEGES.COLLEGE_ID = CHALLENGES.COLLEGE_ID
INNER JOIN CONTESTS
ON CONTESTS.CONTEST_ID = COLLEGES.CONTEST_ID
GROUP BY CONTESTS.CONTEST_ID
),

VS AS
(
SELECT CONTESTS.CONTEST_ID,
       SUM(VIEW_STATS.TOTAL_VIEWS) AS SUM_TV,
       SUM(VIEW_STATS.TOTAL_UNIQUE_VIEWS) AS SUM_TUV
FROM VIEW_STATS
INNER JOIN CHALLENGES
ON CHALLENGES.CHALLENGE_ID = VIEW_STATS.CHALLENGE_ID
INNER JOIN COLLEGES
ON COLLEGES.COLLEGE_ID = CHALLENGES.COLLEGE_ID
INNER JOIN CONTESTS
ON CONTESTS.CONTEST_ID = COLLEGES.CONTEST_ID
GROUP BY CONTESTS.CONTEST_ID
)

SELECT CONTESTS.CONTEST_ID,
       CONTESTS.HACKER_ID,
       CONTESTS.NAME,
       SS.SUM_TS,
       SS.SUM_TAS,
       VS.SUM_TV,
       VS.SUM_TUV
FROM CONTESTS
INNER JOIN SS
ON SS.CONTEST_ID = CONTESTS.CONTEST_ID
INNER JOIN VS
ON VS.CONTEST_ID = CONTESTS.CONTEST_ID
WHERE SS.SUM_TS > 0
AND
SS.SUM_TAS > 0
AND
VS.SUM_TV > 0
AND
VS.SUM_TUV > 0
ORDER BY CONTESTS.CONTEST_ID
