--MS SQL SERVER

WITH PROJECT_START AS
(
SELECT START_DATE,
       ROW_NUMBER() OVER(ORDER BY START_DATE) PSRN
FROM PROJECTS
WHERE START_DATE NOT IN (SELECT END_DATE FROM PROJECTS)
),

PROJECT_END AS
(
SELECT END_DATE,
       ROW_NUMBER() OVER(ORDER BY END_DATE) PERN
FROM PROJECTS
WHERE END_DATE NOT IN (SELECT START_DATE FROM PROJECTS)
)

SELECT PROJECT_START.START_DATE,
       PROJECT_END.END_DATE
FROM PROJECT_START
INNER JOIN PROJECT_END
ON PROJECT_START.PSRN = PROJECT_END.PERN
ORDER BY DATEDIFF(DAY, PROJECT_START.START_DATE, PROJECT_END.END_DATE) ASC,
         PROJECT_START.START_DATE ASC
