--MS SQL SERVER

WITH PROJECT_START AS
(SELECT START_DATE,
        ROW_NUMBER() OVER(ORDER BY START_DATE ASC) AS ROW_NUM
FROM PROJECTS
WHERE START_DATE NOT IN (SELECT END_DATE FROM PROJECTS)),

PROJECT_END AS
(SELECT END_DATE,
        ROW_NUMBER() OVER(ORDER BY END_DATE ASC) AS ROW_NUM
FROM PROJECTS
WHERE END_DATE NOT IN (SELECT START_DATE FROM PROJECTS))

SELECT START_DATE,
       END_DATE
FROM PROJECT_START
INNER JOIN PROJECT_END
ON PROJECT_END.ROW_NUM = PROJECT_START.ROW_NUM
ORDER BY DATEDIFF(DAY, START_DATE, END_DATE) ASC,
         START_DATE ASC
