--MS SQL SERVER

WITH MAX_SCORE AS
(
SELECT HACKER_ID,
       CHALLENGE_ID,
       MAX(SCORE) AS MSCORE
FROM SUBMISSIONS
GROUP BY HACKER_ID,
         CHALLENGE_ID
)

SELECT MAX_SCORE.HACKER_ID,
       HACKERS.NAME,
       SUM(MAX_SCORE.MSCORE)
FROM MAX_SCORE
INNER JOIN HACKERS
ON HACKERS.HACKER_ID = MAX_SCORE.HACKER_ID
GROUP BY MAX_SCORE.HACKER_ID,
         HACKERS.NAME
HAVING SUM(MAX_SCORE.MSCORE) > 0
ORDER BY SUM(MAX_SCORE.MSCORE) DESC,
         MAX_SCORE.HACKER_ID ASC
