--MS SQL SERVER

WITH MX_SCORE AS
(SELECT HACKER_ID,
        CHALLENGE_ID,
        MAX(SCORE) AS MAX_SCORE
FROM SUBMISSIONS
GROUP BY HACKER_ID,
         CHALLENGE_ID)

SELECT MX_SCORE.HACKER_ID,
       NAME,
       SUM(MAX_SCORE) AS TOTAL_SCORE
FROM MX_SCORE
INNER JOIN HACKERS
ON HACKERS.HACKER_ID = MX_SCORE.HACKER_ID
GROUP BY MX_SCORE.HACKER_ID,
         NAME
HAVING SUM(MAX_SCORE) > 0
ORDER BY TOTAL_SCORE DESC,
         MX_SCORE.HACKER_ID ASC
