--MS SQL SERVER

SELECT S.HACKER_ID,
       H.NAME
FROM SUBMISSIONS S
INNER JOIN HACKERS H
ON S.HACKER_ID = H.HACKER_ID
INNER JOIN CHALLENGES C
ON C.CHALLENGE_ID = S.CHALLENGE_ID
INNER JOIN DIFFICULTY D
ON D.DIFFICULTY_LEVEL = C.DIFFICULTY_LEVEL
WHERE S.SCORE = D.SCORE
AND
S.CHALLENGE_ID = C.CHALLENGE_ID
GROUP BY S.HACKER_ID, H.NAME
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC,
         S.HACKER_ID ASC
