--MS SQL SERVER

WITH DOC_TABLE AS
(
SELECT NAME,
       ROW_NUMBER() OVER(ORDER BY NAME) AS RN
FROM OCCUPATIONS
WHERE OCCUPATION LIKE "Doctor"
),

PROF_TABLE AS(
SELECT NAME,
       ROW_NUMBER() OVER(ORDER BY NAME) AS RN
FROM OCCUPATIONS
WHERE OCCUPATION LIKE "Professor"
),

SING_TABLE AS
(
SELECT NAME,
       ROW_NUMBER() OVER(ORDER BY NAME) AS RN
FROM OCCUPATIONS
WHERE OCCUPATION LIKE "Singer"
),

ACT_TABLE AS
(
SELECT NAME,
       ROW_NUMBER() OVER(ORDER BY NAME) AS RN
FROM OCCUPATIONS
WHERE OCCUPATION LIKE "Actor"
)

SELECT DOC_TABLE.NAME,
       PROF_TABLE.NAME,
       SING_TABLE.NAME,
       ACT_TABLE.NAME
FROM PROF_TABLE
LEFT JOIN DOC_TABLE
ON DOC_TABLE.RN = PROF_TABLE.RN
LEFT JOIN SING_TABLE
ON SING_TABLE.RN = PROF_TABLE.RN
LEFT JOIN ACT_TABLE
ON ACT_TABLE.RN = PROF_TABLE.RN
