--MS SQL SERVER

WITH DOCTORS AS
(SELECT NAME,
        ROW_NUMBER() OVER(ORDER BY NAME) AS RN
FROM OCCUPATIONS
WHERE OCCUPATION LIKE "DOCTOR"),

PROFESSORS AS
(SELECT NAME,
        ROW_NUMBER() OVER(ORDER BY NAME) AS RN
FROM OCCUPATIONS
WHERE OCCUPATION LIKE "PROFESSOR"),

SINGERS AS
(SELECT NAME,
        ROW_NUMBER() OVER(ORDER BY NAME) AS RN
FROM OCCUPATIONS
WHERE OCCUPATION LIKE "SINGER"),

ACTORS AS
(SELECT NAME,
        ROW_NUMBER() OVER(ORDER BY NAME) AS RN
FROM OCCUPATIONS
WHERE OCCUPATION LIKE "ACTOR")


SELECT DOCTORS.NAME,
       PROFESSORS.NAME,
       SINGERS.NAME,
       ACTORS.NAME
FROM PROFESSORS
LEFT JOIN DOCTORS
ON PROFESSORS.RN = DOCTORS.RN
LEFT JOIN SINGERS
ON PROFESSORS.RN = SINGERS.RN
LEFT JOIN ACTORS
ON PROFESSORS.RN = ACTORS.RN
