--MS SQL SERVER

SELECT EMPLOYEE.COMPANY_CODE,
       FOUNDER,
       COUNT(DISTINCT LEAD_MANAGER_CODE),
       COUNT(DISTINCT SENIOR_MANAGER_CODE),
       COUNT(DISTINCT MANAGER_CODE),
       COUNT(DISTINCT EMPLOYEE_CODE)
FROM EMPLOYEE
INNER JOIN COMPANY
ON COMPANY.COMPANY_CODE = EMPLOYEE.COMPANY_CODE
GROUP BY FOUNDER,
         EMPLOYEE.COMPANY_CODE
ORDER BY EMPLOYEE.COMPANY_CODE ASC
