--MS SQL SERVER

SELECT NAME
FROM STUDENTS
INNER JOIN FRIENDS
ON FRIENDS.ID = STUDENTS.ID
INNER JOIN PACKAGES P1
ON P1.ID = STUDENTS.ID
INNER JOIN PACKAGES P2
ON P2.ID = FRIENDS.FRIEND_ID
WHERE
P2.SALARY > P1.SALARY
ORDER BY
P2.SALARY ASC
